### ISSUE TITLE
Update maps

### ISSUE THREAD

**Issue by CristianaLavado** [CristianaLavado/YelpCamp#2]
Let show page maps update when campground location is updated.

**Comment by brunor97** [comment]
when creating a new campground, the map coordinates are saved into the DB
https://github.com/CristianaLavado/YelpCamp/blob/faeb308ccebee299e18444c9e68aa3674fa7ff54/controllers/campgrounds.js#L25


but when updating a pre-existing campground this value is never updated
https://github.com/CristianaLavado/YelpCamp/blob/faeb308ccebee299e18444c9e68aa3674fa7ff54/controllers/campgrounds.js#L60
